In [65]:
main_problem = [[4,6,0,0,3,0,0,1,9],
                [8,9,0,1,0,2,0,3,4],
                [0,3,0,0,0,0,6,8,0],
                [1,7,0,0,4,0,0,2,0],
                [9,4,0,7,2,0,0,0,1],
                [0,5,2,0,9,1,0,0,0],
                [0,0,0,0,1,0,0,0,8],
                [5,0,0,6,0,7,0,4,0],
                [0,0,0,2,5,0,1,9,7]]

In [1]:
main_problem = [[int("0") for _ in range(9)],
                [0,0,0,0,0,3,0,8,5],
                [0,0,1,0,2,0,0,0,0],
                [0,0,0,5,0,7,0,0,0],
                [0,0,4,0,0,0,1,0,0],
                [0,9,0,0,0,0,0,0,0],
                [5,0,0,0,0,0,0,7,3],
                [0,0,2,0,1,0,0,0,0],
                [0,0,0,0,4,0,0,0,9]
]

In [2]:
sudoku_array = main_problem.copy()
boxes = [[[0] * 3 for _ in range(3)] for _ in range(9)]
for row_index, row in enumerate(sudoku_array):
  for column_index, element in enumerate(row):
    if element != 0:
      box_index = (row_index // 3) * 3 + (column_index // 3)
      boxes[box_index][row_index % 3][column_index % 3] = element


In [3]:
import numpy as np
print(np.array(boxes).shape)
print(np.array(boxes))

(9, 3, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 3]
  [0 2 0]]

 [[0 0 0]
  [0 8 5]
  [0 0 0]]

 [[0 0 0]
  [0 0 4]
  [0 9 0]]

 [[5 0 7]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 0 0]
  [0 0 0]]

 [[5 0 0]
  [0 0 2]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 4 0]]

 [[0 7 3]
  [0 0 0]
  [0 0 9]]]


In [4]:
boxes_rows = [boxes[i:i+3] for i in range(0,9,3)]
print(len(boxes_rows))

3


In [5]:
for i in range (0,9,3):
    print(boxes[i:i+3])

[[[0, 0, 0], [0, 0, 0], [0, 0, 1]], [[0, 0, 0], [0, 0, 3], [0, 2, 0]], [[0, 0, 0], [0, 8, 5], [0, 0, 0]]]
[[[0, 0, 0], [0, 0, 4], [0, 9, 0]], [[5, 0, 7], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [1, 0, 0], [0, 0, 0]]]
[[[5, 0, 0], [0, 0, 2], [0, 0, 0]], [[0, 0, 0], [0, 1, 0], [0, 4, 0]], [[0, 7, 3], [0, 0, 0], [0, 0, 9]]]


In [49]:
boxes_rows[1][1]

[[0, 4, 0], [7, 2, 0], [0, 9, 1]]

In [50]:
for boxes_row_number, row_of_boxes in enumerate(boxes_rows):
    for box_row_number, box in enumerate(row_of_boxes):
        for row_number, row in enumerate(box):
            for i in range(1,10):
                if i not in row:
                    if i not in main_problem[box_row_number]:
                        pass

In [60]:
for row_number, row in enumerate(sudoku_array):
    for index, element in enumerate(row):
        if element == 0:
            for i in range(1,10):
                if i not in row:
                    if i not in [column[index] for column in sudoku_array]:
                        if i not in [j for n in boxes_rows[row_number//3][index//3] for j in n]:
                            sudoku_array[row_number][index] = i

        

In [61]:
print(sudoku_array)

[[4, 6, 7, 8, 3, 5, 2, 1, 9], [8, 9, 5, 1, 7, 2, 0, 3, 4], [7, 3, 1, 9, 0, 4, 6, 8, 5], [1, 7, 8, 5, 4, 6, 9, 2, 3], [9, 4, 6, 7, 2, 8, 5, 0, 1], [6, 5, 2, 3, 9, 1, 8, 7, 0], [3, 2, 9, 4, 1, 0, 0, 6, 8], [5, 8, 3, 6, 0, 7, 0, 4, 2], [0, 0, 4, 2, 5, 3, 1, 9, 7]]


In [62]:
sudoku_array

[[4, 6, 7, 8, 3, 5, 2, 1, 9],
 [8, 9, 5, 1, 7, 2, 0, 3, 4],
 [7, 3, 1, 9, 0, 4, 6, 8, 5],
 [1, 7, 8, 5, 4, 6, 9, 2, 3],
 [9, 4, 6, 7, 2, 8, 5, 0, 1],
 [6, 5, 2, 3, 9, 1, 8, 7, 0],
 [3, 2, 9, 4, 1, 0, 0, 6, 8],
 [5, 8, 3, 6, 0, 7, 0, 4, 2],
 [0, 0, 4, 2, 5, 3, 1, 9, 7]]

In [6]:
def is_valid(board, row, col, num):
    # Check if the number is not in the current row
    if num in board[row]:
        return False
    
    # Check if the number is not in the current column
    if num in [board[i][col] for i in range(9)]:
        return False
    
    # Check if the number is not in the current 3x3 grid
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(start_row, start_row + 3):
        for j in range(start_col, start_col + 3):
            if board[i][j] == num:
                return False
    return True

def solve_sudoku(board):
    for row in range(9):
        for col in range(9):
            # If the cell is empty
            if board[row][col] == 0:
                # Try filling the cell with numbers from 1 to 9
                for num in range(1, 10):
                    if is_valid(board, row, col, num):
                        board[row][col] = num
                        # Recur with the updated board
                        if solve_sudoku(board):
                            return True 
                        # If the recursion does not lead to a solution, backtrack
                        board[row][col] = 0
                # If no number is valid, return to the previous recursive call and backtrack
                return False
    # If all cells are filled, the puzzle is solved
    return True

if solve_sudoku(main_problem):
    for row in main_problem:
        print(row)

KeyboardInterrupt: 

In [64]:
main_problem

[[4, 6, 7, 8, 3, 5, 2, 1, 9],
 [8, 9, 5, 1, 7, 2, 0, 3, 4],
 [7, 3, 1, 9, 0, 4, 6, 8, 5],
 [1, 7, 8, 5, 4, 6, 9, 2, 3],
 [9, 4, 6, 7, 2, 8, 5, 0, 1],
 [6, 5, 2, 3, 9, 1, 8, 7, 0],
 [3, 2, 9, 4, 1, 0, 0, 6, 8],
 [5, 8, 3, 6, 0, 7, 0, 4, 2],
 [0, 0, 4, 2, 5, 3, 1, 9, 7]]

In [1]:
print("""[[4,6,0,0,3,0,0,1,9],
                [8,9,0,1,0,2,0,3,4],
                [0,3,0,0,0,0,6,8,0],
                [1,7,0,0,4,0,0,2,0],
                [9,4,0,7,2,0,0,0,1],
                [0,5,2,0,9,1,0,0,0],
                [0,0,0,0,1,0,0,0,8],
                [5,0,0,6,0,7,0,4,0],
                [0,0,0,2,5,0,1,9,7]]""".replace('[', '{').replace(']', '}'))

{{4,6,0,0,3,0,0,1,9},
                {8,9,0,1,0,2,0,3,4},
                {0,3,0,0,0,0,6,8,0},
                {1,7,0,0,4,0,0,2,0},
                {9,4,0,7,2,0,0,0,1},
                {0,5,2,0,9,1,0,0,0},
                {0,0,0,0,1,0,0,0,8},
                {5,0,0,6,0,7,0,4,0},
                {0,0,0,2,5,0,1,9,7}}
